### ISSUE TITLE
How to set __meteor_runtime_config__.DDP_DEFAULT_CONNECTION_URL ?

### ISSUE THREAD

**Issue by triasrahman** [idanwe/meteor-client-side#29] opened 2016-09-11 08:44 UTC
How to set **meteor_runtime_config**.DDP_DEFAULT_CONNECTION_URL ? I implement it on ionic 2. Please give the informative documentation.

Thanks!

**Comment by idanwe** [comment] 2016-09-12 07:45
@triasrahman I close this as it looks duplicate of #28 , lets continue there

**Closed as completed by idanwe** 2016-09-12 07:45 UTC
Labels: duplicate, question
