### ISSUE TITLE
log in problrm

### ISSUE THREAD

**Issue by gaykan** [idanwe/meteor-client-side#8] opened 2015-12-26 16:33 UTC
I can create users but when logging in, I get 

_Error: Match failed [400]_

Using : 
_angular meteor ==> 1.3.1
ionic ==> 1.2.1_

Call : 
_var email = "aaa@bbb.com";
var password = "lqwşqwdxşq"; 
$meteor.loginWithPassword(email, password, function(error){
      if(error){
        console.log(error.reason);
      } else {
        alert ('OK');
      }
    });_

Working createUser ==>
- $meteor.createUser({
    username: $scope.user.username,
    email: $scope.user.email,
    password: $scope.user.passphrase
  }).then(function () {
    console.log('Login success');
  }, function (err) {
    console.log('Login error - ', err);
  });*

**Comment by idanwe** [comment] 2015-12-27 22:54
The problem is with angular-meteor 1.3.1 bundle.
It will be fixed with angular-meteor 1.3.2 release

**Comment by gaykan** [comment] 2015-12-29 18:04
I upgraded, but it is still the same, but I get two different messages for login.

**For a previously created I get**

> *Error: Match failed [400]
> column: 26050
> details: undefined
> error: 400
> errorType: "Meteor.Error"
> line: 1
> message: "Match failed [400]"
> reason: "Match failed"

**For a create and in success code  loginWithPassword I get ( no problem on createUser )**

> _Error: string.charCodeAt is not a function. (In 'string.charCodeAt(n)', 'string.charCodeAt' is undefined)
> Utf8Encode@http://localhost:8100/lib/accounts-password-client-side.bundle.min.js:1:2442
> SHA256@http://localhost:8100/lib/accounts-password-client-side.bundle.min.js:1:2985
> _hashPassword@http://localhost:8100/lib/accounts-password-client-side.bundle.min.js:1:27418
> loginWithPassword@http://localhost:8100/lib/accounts-password-client-side.bundle.min.js:1:27073
> http://localhost:8100/lib/angular-meteor-1.3.2/dist/angular-meteor.bundle.js:10912:24_

**Comment by idanwe** [comment] 2016-07-08 12:01
@gaykan did you solved it?

**Comment by idanwe** [comment] 2016-09-12 07:51
@gaykan I'm closing this for now, if it is still relevant please re-open it

**Closed as completed by idanwe** 2016-09-12 07:51 UTC

**Comment by teerachel** [comment] 2017-02-10 04:23
@idanwe I am experiencing the same error and I've no idea how to solve it. :( Please help! Thanks
